# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  fmt = {
    pname = "fmt";
    version = "11.1.3";
    src = fetchFromGitHub {
      owner = "fmtlib";
      repo = "fmt";
      rev = "11.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-6r9D/csVSgS+T/H0J8cSR+YszxnH/h2V2odi2s6VYN8=";
    };
  };
  reflect-cpp = {
    pname = "reflect-cpp";
    version = "v0.17.0";
    src = fetchFromGitHub {
      owner = "getml";
      repo = "reflect-cpp";
      rev = "v0.17.0";
      fetchSubmodules = false;
      sha256 = "sha256-ugMop4Gsw46zFA7mESNzDTAZVzIg3szAX8ND1kUiF2A=";
    };
  };
  sdbus-cpp = {
    pname = "sdbus-cpp";
    version = "v2.1.0";
    src = fetchFromGitHub {
      owner = "kistler-group";
      repo = "sdbus-cpp";
      rev = "v2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-JnjabBr7oELLsUV9a+dAAaRyUzaMIriu90vkaVJg2eY=";
    };
  };
  tomlplusplus = {
    pname = "tomlplusplus";
    version = "v3.4.0";
    src = fetchFromGitHub {
      owner = "marzer";
      repo = "tomlplusplus";
      rev = "v3.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-h5tbO0Rv2tZezY58yUbyRVpsfRjY3i+5TPkkxr6La8M=";
    };
  };
  yyjson = {
    pname = "yyjson";
    version = "0.10.0";
    src = fetchFromGitHub {
      owner = "ibireme";
      repo = "yyjson";
      rev = "0.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-mp9Oz08qTyhj3P6F1d81SX96vamUY/JWpD2DTYR+v04=";
    };
  };
}
