# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchFromGitHub,
}: {
  dbus-cxx = {
    pname = "dbus-cxx";
    version = "2.5.2";
    src = fetchFromGitHub {
      owner = "dbus-cxx";
      repo = "dbus-cxx";
      rev = "2.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-if/9XIsf3an5Sij91UIIyNB3vlFAcKrm6YT5Mk7NhB0=";
    };
  };
}
