name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux
    runs-on: native-linux
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Build glibc-generic package
        id: build_glibc
        run: echo "path=$(nix build .#glibc-generic --no-link --print-out-paths)" >> $GITHUB_OUTPUT
        shell: fish

      - name: Push glibc-generic to Cachix
        run: cachix push pupbrained ${{ steps.build_glibc.outputs.path }}
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
          shell: fish

      - name: Build musl-generic package
        id: build_musl
        run: echo "path=$(nix build .#musl-generic --no-link --print-out-paths)" >> $GITHUB_OUTPUT
        shell: fish

      - name: Push musl-generic to Cachix
        run: cachix push pupbrained ${{ steps.build_musl.outputs.path }}
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
        shell: fish

      - name: Upload Nix glibc-generic Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nix-build-glibc-generic
          path: ${{ steps.build_glibc.outputs.path }}/bin/draconis++

      - name: Upload Nix musl-generic Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nix-build-musl-generic
          path: ${{ steps.build_musl.outputs.path }}/bin/draconis++
  windows:
    name: Windows
    runs-on: native
    steps:
      - name: Display Workspace Info & Define Persistent Path
        id: paths
        run: |
          echo "GITHUB_WORKSPACE (source checkout location): ${{ github.workspace }}"
          $persistentBuildDir = "C:\persistent_builds\${{ github.event.repository.name }}"
          echo "Persistent Build Directory will be: $persistentBuildDir"
          echo "build_dir=$persistentBuildDir" | Add-Content -Path $env:GITHUB_OUTPUT
        shell: powershell

      - uses: actions/checkout@v4

      - name: Ensure Persistent Build Directory Exists
        run: New-Item -ItemType Directory -Force -Path "${{ steps.paths.outputs.build_dir }}"
        shell: powershell

      - name: Setup Meson Build in Persistent Directory
        run: >
          meson setup "${{ steps.paths.outputs.build_dir }}" . --buildtype=release
          -Dc_args="-fuse-ld=lld"
          -Dcpp_args="-fuse-ld=lld"
          -Dc_link_args="-fuse-ld=lld"
          -Dcpp_link_args="-fuse-ld=lld"
        shell: powershell

      - name: Compile with Meson in Persistent Directory
        run: meson compile -C "${{ steps.paths.outputs.build_dir }}"
        shell: powershell

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: "${{ steps.paths.outputs.build_dir }}\\draconis++.exe"
