name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
      fail-fast: false
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'rampage'
          witness-carnage: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            build-dir = /nix/tmp
      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: pupbrained
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Nix Build and Push Packages
        run: |
          nix build .#glibc-generic --no-link --print-out-paths | cachix push pupbrained
          nix build .#musl-generic --no-link --print-out-paths | cachix push pupbrained
      - name: Nix Develop and Push Dev Shell
        run: |
          nix develop --profile dev-profile -c true
          cachix push pupbrained dev-profile
